name: Build

on:
  push:
    branches:
      - main
      - f/*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Slack Notification
        uses: act10ns/slack@v2
        with:
          status: starting

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build main webapp
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build canary webapp
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/heads/f/')
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:canary
          labels: ${{ steps.meta.outputs.labels }}

      - name: Slack Notification
        uses: act10ns/slack@v2
        if: always()
        with:
          status: ${{ job.status }}
